import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Providers
import { SupabaseAuthProvider } from "@/components/providers/supabase-auth-provider";
import { ConvexSupabaseProvider } from "@/components/providers/convex-query-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";

// Styles
import "@/app/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SupabaseAuthProvider>
          <ConvexSupabaseProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </ConvexSupabaseProvider>
        </SupabaseAuthProvider>
      </body>
    </html>
  );
}
